import { Genre } from './genre';

export let GenreList = [
  new Genre('Action', 1),
  new Genre('Adventure', 2),
  new Genre('Cars', 3),
  new Genre('Comedy', 4),
  new Genre('Dementia', 5),
  new Genre('Demons', 6),
  new Genre('Mystery', 7),
  new Genre('Drama', 8),
  new Genre('Ecchi', 9),
  new Genre('Fantasy', 10),
  new Genre('Game', 11),
  new Genre('Hentai', 12),
  new Genre('Historical', 13),
  new Genre('Horror', 14),
  new Genre('Kids', 15),
  new Genre('Magic', 16),
  new Genre('Martial Arts', 17),
  new Genre('Mecha', 18),
  new Genre('Music', 19),
  new Genre('Parody', 20),
  new Genre('Samurai', 21),
  new Genre('Romance', 22),
  new Genre('School', 23),
  new Genre('Sci Fi', 24),
  new Genre('Shoujo Ai', 25),
  new Genre('Shounen', 26),
  new Genre('Shounen Ai', 27),
  new Genre('Space', 28),
  new Genre('Sports', 29),
  new Genre('Super Power', 30),
  new Genre('Vampire', 31),
  new Genre('Yaoi', 32),
  new Genre('Yuri', 33),
  new Genre('Yaoi', 34),
  new Genre('Harem', 35),
  new Genre('Supernatural', 36),
  new Genre('Military', 37),
  new Genre('Police', 38),
  new Genre('Military', 39),
  new Genre('Psychological', 40),
  new Genre('Thriller', 41),
  new Genre('Seinen', 42),
  new Genre('Josei', 43),
];
